/**
 * Server-only Shopify Storefront API client.
 *
 * SHOPIFY_STOREFRONT_ACCESS_TOKEN must contain the private token generated by
 * Shopify's Headless channel. It is sent only in Shopify's private-token
 * header and must never use a NEXT_PUBLIC_* environment variable.
 */

interface ShopifyGraphQLError {
  message: string;
}

interface ShopifyPayload<T> {
  data?: T;
  errors?: ShopifyGraphQLError[];
}

interface ShopifyFetchOptions {
  revalidate?: number;
}

export class ShopifyRequestError extends Error {
  readonly status?: number;

  constructor(message: string, status?: number) {
    super(message);
    this.name = "ShopifyRequestError";
    this.status = status;
  }
}

function getShopifyConfig() {
  const domain = process.env.SHOPIFY_STORE_DOMAIN;
  const privateToken = process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN;
  const version = process.env.SHOPIFY_STOREFRONT_API_VERSION || "2026-07";

  if (!domain || !privateToken) {
    throw new ShopifyRequestError(
      "Shopify Storefront API credentials are not configured.",
    );
  }

  return { domain, privateToken, version };
}

export async function shopifyFetch<T>(
  query: string,
  variables: Record<string, unknown> = {},
  options: ShopifyFetchOptions = {},
): Promise<T> {
  const { domain, privateToken, version } = getShopifyConfig();
  const response = await fetch(
    `https://${domain}/api/${version}/graphql.json`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Shopify-Storefront-Private-Token": privateToken,
      },
      body: JSON.stringify({ query, variables }),
      next: { revalidate: options.revalidate ?? 300 },
    },
  );

  if (!response.ok) {
    throw new ShopifyRequestError(
      `Shopify Storefront API returned ${response.status}.`,
      response.status,
    );
  }

  const payload = (await response.json()) as ShopifyPayload<T>;

  if (!payload.data || payload.errors?.length) {
    throw new ShopifyRequestError(
      payload.errors?.map((error) => error.message).join("; ") ||
        "Shopify response did not contain data.",
    );
  }

  return payload.data;
}

export interface ShopifyConnectionSnapshot {
  shop: {
    name: string;
    primaryDomain: { url: string };
  };
  localization: {
    country: {
      isoCode: string;
      currency: { isoCode: string };
    };
    availableCountries: Array<{
      isoCode: string;
      currency: { isoCode: string };
    }>;
    availableLanguages: Array<{
      isoCode: string;
      endonymName: string;
    }>;
  };
  products: {
    nodes: Array<{ id: string; handle: string; title: string }>;
  };
}

const connectionQuery = `#graphql
  query ShopifyConnectionSnapshot {
    shop {
      name
      primaryDomain { url }
    }
    localization {
      country {
        isoCode
        currency { isoCode }
      }
      availableCountries {
        isoCode
        currency { isoCode }
      }
      availableLanguages {
        isoCode
        endonymName
      }
    }
    products(first: 1) {
      nodes { id handle title }
    }
  }
`;

export function getShopifyConnectionSnapshot() {
  return shopifyFetch<ShopifyConnectionSnapshot>(connectionQuery, {}, {
    revalidate: 60,
  });
}
